version: "3"

services:

  # Monitoring & Updates
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    command:
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    environment:
      TZ: $TZ

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    environment:
      TZ: $TZ

  smartctl:
    image: matusnovak/prometheus-smartctl:latest
    container_name: smartctl
    restart: unless-stopped
    ports:
      - 9902:9902
    privileged: true

  nut:
    image: upshift/nut-upsd
    container_name: nut
    restart: unless-stopped
    environment:
      UPS_DESC: CyberPower 1500VA UPS
      SHUTDOWN_CMD: pwd
    ports:
      - 3493:3493
    privileged: true

  # Media
  rtorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent
    restart: unless-stopped
    ports:
      - 8000:8000   # XMLRPC (*arr)
      - 8085:8080   # RUTORRENT (web)
      - 50000:50000 # PEERING
    volumes:
      - $OPDIR/rtorrent/data/geoip:/data/geoip
      - $OPDIR/rtorrent/data/rtorrent:/data/rtorrent
      - $OPDIR/rtorrent/data/rutorrent:/data/rutorrent
      - $DATADIR/Seeds:/data/Seeds
    stop_grace_period: 15s
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    volumes:
      - $OPDIR/prowlarr:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - $OPDIR/sonarr:/config
      - $DATADIR:/data
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - $OPDIR/radarr:/config
      - $DATADIR:/data
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    hostname: calibre-web
    restart: unless-stopped
    ports:
      - 8083:8083
    volumes:
      - $OPDIR/calibre-web:/config
      - $DATADIR/Books:/data/Books
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DOCKER_MODS: linuxserver/calibre-web:universal-calibre

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    volumes:
      - $OPDIR/nextcloud/config:/config
      - $OPDIR/nextcloud/data:/data
      - $DATADIR:/mnt/celebrimbor
      - $OPDIR/syncthing/data:/mnt/syncthing
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    ports:
      - 4431:80

  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    restart: unless-stopped
    ports:
      - 8384:8384
    volumes:
      - $OPDIR/syncthing:/var/syncthing
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  # Media
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    ports:
      - 5055:5055
    volumes:
      - $OPDIR/overseerr:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  # Games
  foundry-kirkwall:
    image: felddy/foundryvtt:release
    container_name: foundry-kirkwall
    hostname: foundry-kirkwall
    restart: unless-stopped
    ports:
      - 30000:30000
    volumes:
      - $OPDIR/kirkwall:/data
    environment:
      TIMEZONE: $TZ
      FOUNDRY_UID: $PUID
      FOUNDRY_GID: $PGID
      FOUNDRY_HOSTNAME: kirkwall.$DOMAIN
    env_file: $OPDIR/kirkwall/config.env

  # Other
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    hostname: homeassistant
    restart: unless-stopped
    privileged: true
    network_mode: host
    ports:
      - 8123:8123
    volumes:
      - $OPDIR/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DOCKER_MODS: linuxserver/mods:universal-package-install
      INSTALL_PACKAGES: nmap # for nmap device tracker

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    hostname: code-server
    restart: unless-stopped
    ports:
      - 8443:8443
    volumes:
      - $OPDIR/code:/config
      - $OPDIR:/opt
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      SUDO_PASSWORD: $CODE_PASSWORD
      DOCKER_MODS: linuxserver/mods:code-server-python3
