version: "3"

networks:
  wasabi-overlay:
    external: true

services:

  # Monitoring & Updates
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    networks:
      - wasabi-overlay
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=$TZ
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=$WATCHTOWER_NOTIFICATION_URL
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info

  node-exporter:
    image: prom/node-exporter
    container_name: node-celebrimbor
    hostname: node-celebrimbor
    restart: unless-stopped
    networks:
      - wasabi-overlay
    expose:
      - 9100
    command:
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor-celebrimbor
    hostname: cadvistor-celebrimbor
    restart: unless-stopped
    networks:
      - wasabi-overlay
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    environment:
      - TZ=$TZ

  scrutiny:
    image: analogj/scrutiny
    container_name: scrutiny
    restart: unless-stopped
    networks:
      - wasabi-overlay
    expose:
      - 8080
    volumes:
      - $OPDIR/scrutiny:/scrutiny/config
      - /run/udev:/run/udev:ro
    devices:
      - /dev/sda
      - /dev/sdc
      - /dev/sdd
      - /dev/sde
      - /dev/sdf
    cap_add:
      - SYS_RAWIO
    labels:
      - traefik.enable=true
      - traefik.http.routers.scrutiny.entrypoints=websecure
      - traefik.http.routers.scrutiny.rule=Host(`scrutiny.$DOMAIN`)
      - traefik.http.routers.scrutiny.middlewares=authelia@file
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID