version: "3"

networks:
  wasabi-overlay:
    external: true

services:

  # Monitoring & Updates
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    networks:
      - wasabi-overlay
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=$TZ
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=$WATCHTOWER_NOTIFICATION_URL
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info

  node-exporter:
    image: prom/node-exporter
    container_name: node-celebrimbor
    hostname: node-celebrimbor
    restart: unless-stopped
    networks:
      - wasabi-overlay
    expose:
      - 9100
    command:
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
