version: "3"

services:

  traefik:
    image: traefik:v2.6
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $OPDIR/traefik:/etc/traefik
    environment:
      - CF_DNS_API_TOKEN_FILE=/etc/traefik/CF_DNS_API_TOKEN
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.rule=Host(`traefik.$DOMAIN`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=auth-adminonly-basic@file

  whoami:
    image: traefik/whoami
    container_name: simple-service
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=Host(`whoami.$DOMAIN`)

networks:
  default:
    external:
      name: wasabi
