version: "3"

services:

  # Monitoring & Updates
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-ereinion
    hostname: node-ereinion
    restart: unless-stopped
    ports:
      - 9100:9100
    command:
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-ereinion
    hostname: cadvistor-ereinion
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    environment:
      TZ: $TZ

  # Communication
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    container_name: synapse
    hostname: synapse
    restart: unless-stopped
    ports:
      - 8008:8008
      - 9000:9000
    volumes:
      - $OPDIR/synapse:/data
    environment:
      TZ: $TZ
      UID: $PUID
      GID: $PGID
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    depends_on:
      - postgres-matrix

  postgres-matrix:
    image: docker.io/postgres:12-alpine
    container_name: postgres-synapse
    restart: unless-stopped
    user: $PUID:$PGID # postgres will not init database as 1000:1000
    expose:
      - 5432
    volumes:
      - $OPDIR/postgres-matrix:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: $MATRIX_POSTGRES_PASSWORD
      # https://matrix-org.github.io/synapse/latest/postgres.html#set-up-database
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C

  element:
    image: vectorim/element-web:latest
    container_name: element
    restart: unless-stopped
    ports:
      - 8183:80
    volumes:
      - $OPDIR/element/config.json:/app/config.json:ro
    environment:
      TZ: $TZ

  heisenbridge:
    image: hif1/heisenbridge:latest
    container_name: heisenbridge
    restart: unless-stopped
    expose:
      - 9898
    volumes:
      - $OPDIR/synapse/heisenbridge:/data
    command: -v -c /data/heisenbridge.yaml http://synapse:8008
    depends_on:
      - synapse

  # Games
  foundry-kirkwall:
    image: felddy/foundryvtt:release
    container_name: foundry-kirkwall
    hostname: foundry-kirkwall
    restart: unless-stopped
    ports:
      - 30000:30000
    volumes:
      - $OPDIR/kirkwall:/data
    environment:
      TIMEZONE: $TZ
      FOUNDRY_UID: $PUID
      FOUNDRY_GID: $PGID
      FOUNDRY_HOSTNAME: kirkwall.$DOMAIN
    env_file: $OPDIR/kirkwall/config.env

  # Media
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    ports:
      - 5055:5055
    volumes:
      - $OPDIR/overseerr:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  # Other
  code-ereinion:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-ereinion
    hostname: code-ereinion
    restart: unless-stopped
    ports:
      - 8443:8443
    volumes:
      - $OPDIR/code:/config
      - $OPDIR:/opt
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      SUDO_PASSWORD: $CODE_PASSWORD
      DOCKER_MODS: linuxserver/mods:universal-package-install
      INSTALL_PACKAGES: sqlite3
