version: "3"

networks:
  wasabi:
    driver: bridge

services:

  # Networking
  traefik:
    image: traefik:v2.6
    container_name: traefik
    restart: unless-stopped
    networks:
      - wasabi
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $OPDIR/traefik:/etc/traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.rule=Host(`traefik.$DOMAIN`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=authelia@file
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN

  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    networks:
      - wasabi
    expose:
      - 9091
    volumes:
      - /opt/authelia:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.tls=true
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.rule=Host(`auth.$DOMAIN`)
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID

  nginx:
    image: lscr.io/linuxserver/nginx
    container_name: nginx
    restart: unless-stopped
    networks:
      - wasabi
    expose:
      - 443
    volumes:
      - $OPDIR/nginx:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.rule=Host(`$DOMAIN`)
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID

  protonmail:
    image: shenxn/protonmail-bridge
    container_name: protonmail
    restart: unless-stopped
    networks:
      - wasabi
    expose:
      - 25
      - 143
    volumes:
      - $OPDIR/protonmail:/root
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
