version: "3"

networks:
  wasabi:
    driver: bridge

services:

  traefik:
    image: traefik:v2.6
    container_name: traefik
    networks:
      - wasabi
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $OPDIR/traefik:/etc/traefik
    environment:
      - TZ=$TZ
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.rule=Host(`traefik.$DOMAIN`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=authelia@file
    restart: unless-stopped

  authelia:
    image: authelia/authelia
    container_name: authelia
    networks:
      - wasabi
    volumes:
      - /opt/authelia:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.tls=true
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.rule=Host(`auth.$DOMAIN`)
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - AUTHELIA_JWT_SECRET_FILE=/config/jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/config/session_secret
