version: "2.4"

networks:
  valinor-v6:
    name: valinor-v6
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:b::/64
          gateway: 2001:db8:b::1

services:

  # Networking
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - 4080:80
      - 4443:443
    volumes:
      - $OPDIR/nginx:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  # Monitoring & Updates
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - $OPDIR/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - $OPDIR/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
    environment:
      TZ: $TZ
      PUID: $PUID # does this work?
      PGID: $PGID

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    hostname: node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    command:
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    environment:
      TZ: $TZ

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    hostname: cadvistor
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    environment:
      TZ: $TZ

  loki:
    image: grafana/loki
    container_name: loki
    hostname: loki
    restart: unless-stopped
    ports:
      - 3100:3100
    environment:
      TZ: $TZ
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    container_name: promtail
    hostname: promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
    environment:
      TZ: $TZ
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana-oss:main
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    user: $PUID:$PGID
    ports:
      - 3000:3000
    volumes:
      - $OPDIR/grafana:/var/lib/grafana
    environment:
      TZ: $TZ
      GF_PATHS_CONFIG: /var/lib/grafana/grafana.ini

  # Media
  owncast:
    image: gabekangas/owncast:latest
    container_name: owncast
    restart: unless-stopped
    ports:
      - 8084:8080
      - 1935:1935 # RSTP is not exposed to internet, just tailscale
    volumes:
      - $OPDIR/owncast:/app/data
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    restart: unless-stopped
    networks:
      - valinor-v6 # outgoing oauth connections
    ports:
      - 8181:8181
    volumes:
      - $OPDIR/tautulli:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    networks:
      - valinor-v6 # outgoing oauth connections, media lookups
    ports:
      - 5055:5055
    volumes:
      - $OPDIR/overseerr:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    networks:
      - valinor-v6
    ports:
      - 8524:80
    volumes:
      - $OPDIR/freshrss/data:/var/www/FreshRSS/data
      - $OPDIR/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      CRON_MIN: 13,43

  rss-bridge:
    image: rssbridge/rss-bridge:latest
    container_name: rss-bridge
    hostname: rss-bridge
    restart: unless-stopped
    networks:
      - valinor-v6
    ports:
      - 3060:80
    volumes:
      - $OPDIR/freshrss/bridge:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID

  # Other
  foundry-kirkwall:
    image: felddy/foundryvtt:release
    container_name: foundry-kirkwall
    hostname: foundry-kirkwall
    #restart: unless-stopped
    networks:
      - valinor-v6 # TBD, probably needs an address to grab new relases
    ports:
      - 30000:30000
    volumes:
      - $OPDIR/kirkwall:/data
    environment:
      TIMEZONE: $TZ
      FOUNDRY_UID: $PUID
      FOUNDRY_GID: $PGID
      FOUNDRY_HOSTNAME: kirkwall.$DOMAIN
    env_file: $OPDIR/kirkwall/config.env

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    hostname: code-server
    restart: unless-stopped
    networks:
      - valinor-v6 # needs an address for outbound shell stuff
    ports:
      - 8443:8443
    volumes:
      - $OPDIR/code:/config
      - $OPDIR:/opt
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      SUDO_PASSWORD: $CODE_PASSWORD
      DOCKER_MODS: linuxserver/mods:universal-package-install
      INSTALL_PACKAGES: command-not-found|dnsutils|iputils-ping|sqlite3|python3

