services:
    # Networking & Static Sites
    nginx:
        image: lscr.io/linuxserver/nginx:1.28.0
        container_name: nginx
        hostname: nginx
        restart: unless-stopped
        ports:
            - 4080:80
            - 4443:443
        volumes:
            - $OPDIR/nginx:/config
        environment:
            TZ: $TZ
            PUID: $PUID
            PGID: $PGID

    # Monitoring
    prometheus:
        image: prom/prometheus:v3.8.1
        container_name: prometheus
        restart: unless-stopped
        ports:
            - 9090:9090
        volumes:
            - $OPDIR/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
            - $OPDIR/prometheus/data:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=1y"
        environment:
            TZ: $TZ
            PUID: $PUID # does this work?
            PGID: $PGID

    node-exporter:
        image: prom/node-exporter:v1.10.2
        container_name: node-exporter
        hostname: node-exporter
        restart: unless-stopped
        ports:
            - 9100:9100
        command:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        environment:
            TZ: $TZ

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.55.1
        container_name: cadvisor
        hostname: cadvisor
        restart: unless-stopped
        ports:
            - 8080:8080
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        environment:
            TZ: $TZ

    ping-exporter:
        image: czerwonk/ping_exporter:v1.1.4
        container_name: ping-exporter
        restart: unless-stopped
        ports:
            - 9427:9427
        volumes:
            - $OPDIR/prometheus/config/ping_exporter:/config:ro

    nginx-exporter:
        image: quay.io/martinhelmich/prometheus-nginxlog-exporter:v1.11.0
        container_name: nginx-exporter
        restart: unless-stopped
        ports:
            - 4040:4040
        volumes:
            - $OPDIR/nginx/log/nginx:/mnt/nginxlogs:ro
            - $OPDIR/prometheus/config/nginx-exporter/config.yml:/mnt/config.yml:ro
        command: -config-file /mnt/config.yml

    heartbeat:
        build: $OPDIR/dockerfiles/heartbeat
        container_name: heartbeat
        restart: unless-stopped
        environment:
            ENDPOINT_URL: https://status.wasabipesto.com/api/push/BVkRChC75QmplJPcwrujvTze94695UlQ

    alloy:
        image: grafana/alloy:v1.12.1
        container_name: alloy
        restart: unless-stopped
        volumes:
            - $OPDIR/prometheus/config/alloy-config.alloy:/etc/alloy/config.alloy:ro
            - /var/log/journal:/var/log/journal:ro
            - /etc/machine-id:/etc/machine-id:ro
        environment:
            TZ: $TZ

    loki:
        image: grafana/loki:3.6.3
        container_name: loki
        hostname: loki
        restart: unless-stopped
        volumes:
            - $OPDIR/loki/data:/loki/data
            - $OPDIR/loki/config/loki-config.yaml:/config.yaml:ro
        ports:
            - 3100:3100
        environment:
            TZ: $TZ

    grafana:
        image: grafana/grafana-oss:12.3.1
        container_name: grafana
        hostname: grafana
        restart: unless-stopped
        user: $PUID:$PGID
        ports:
            - 3000:3000
        volumes:
            - $OPDIR/grafana:/var/lib/grafana
        environment:
            TZ: $TZ
            GF_PATHS_CONFIG: /var/lib/grafana/grafana.ini

    changedetection:
        image: ghcr.io/dgtlmoon/changedetection.io:0.51.4
        container_name: changedetection
        hostname: changedetection
        restart: unless-stopped
        user: $PUID:$PGID
        ports:
            - 5000:5000
        volumes:
            - $OPDIR/changedetection:/datastore
        environment:
            TZ: $TZ

    tautulli:
        image: lscr.io/linuxserver/tautulli:2.16.0
        container_name: tautulli
        hostname: tautulli
        restart: unless-stopped
        ports:
            - 8181:8181
        volumes:
            - $OPDIR/tautulli:/config
        environment:
            TZ: $TZ
            PUID: $PUID
            PGID: $PGID

    overseerr:
        image: sctx/overseerr:1.34.0
        container_name: overseerr
        restart: unless-stopped
        ports:
            - 5055:5055
        volumes:
            - $OPDIR/overseerr:/app/config
        environment:
            TZ: $TZ
            PUID: $PUID
            PGID: $PGID

    freshrss:
        image: freshrss/freshrss:1.27.1
        container_name: freshrss
        hostname: freshrss
        restart: unless-stopped
        ports:
            - 8524:80
        volumes:
            - $OPDIR/freshrss/data:/var/www/FreshRSS/data
            - $OPDIR/freshrss/extensions:/var/www/FreshRSS/extensions
        environment:
            TZ: $TZ
            PUID: $PUID
            PGID: $PGID
            CRON_MIN: 13,43

    rss-bridge:
        image: rssbridge/rss-bridge:2023-09-24
        container_name: rss-bridge
        hostname: rss-bridge
        restart: unless-stopped
        ports:
            - 3060:80
        volumes:
            - $OPDIR/freshrss/bridge:/config
        environment:
            TZ: $TZ
            PUID: $PUID
            PGID: $PGID

    # Automeme
    automeme:
        build: $OPDIR/automeme
        container_name: automeme
        restart: unless-stopped
        ports:
            - 8888:8888

    # Nice
    nice-postgres:
        image: postgres:18.1
        shm_size: 1g # https://stackoverflow.com/questions/56751565
        container_name: nice-postgres
        hostname: nice-postgres
        restart: unless-stopped
        ports:
            - 5469:5432
        volumes:
            - $OPDIR/nice/postgres_data:/var/lib/postgresql
        environment:
            TZ: $TZ
            POSTGRES_USER: nice
            POSTGRES_PASSWORD: $NICE_POSTGRES_PASSWORD

    nice-api:
        build:
            context: $OPDIR/nice
            dockerfile: api/Dockerfile
        container_name: nice-api
        restart: unless-stopped
        ports:
            - 3070:8000
        depends_on:
            - nice-postgres
        environment:
            ROCKET_ADDRESS: "0.0.0.0"
            DATABASE_URL: $NICE_DATABASE_URL

    nice-postgrest:
        image: postgrest/postgrest:v13.0.8
        container_name: nice-postgrest
        hostname: nice-postgrest
        restart: unless-stopped
        ports:
            - 3071:3000
        depends_on:
            - nice-postgres
        environment:
            PGRST_DB_ANON_ROLE: web_anon
            PGRST_DB_URI: $NICE_DATABASE_URL
            PGRST_JWT_SECRET: $NICE_JWT_SECRET

    nice-pgbackups:
        image: prodrigestivill/postgres-backup-local:18
        container_name: nice-pgbackups
        restart: always
        user: $PUID:$PGID
        volumes:
            - $OPDIR/nice/postgres_backups:/backups
        depends_on:
            - nice-postgres
        environment:
            POSTGRES_HOST: nice-postgres
            POSTGRES_DB: nice
            POSTGRES_USER: nice
            POSTGRES_PASSWORD: $NICE_POSTGRES_PASSWORD
            POSTGRES_EXTRA_OPTS: -Z6
            SCHEDULE: "@daily"
            BACKUP_KEEP_DAYS: 10
            BACKUP_KEEP_WEEKS: 10
            BACKUP_KEEP_MONTHS: 10
            HEALTHCHECK_PORT: 8080

    # Sandiego
    sandiego-fetch:
        build: $OPDIR/sandiego
        container_name: sandiego
        restart: unless-stopped
        volumes:
            - $OPDIR/sandiego/secrets:/usr/src/secrets
            - $OPDIR/sandiego/configuration.yml:/usr/src/configuration.yml:ro
        user: $PUID:$PGID
        depends_on:
            - sandiego-postgres
        env_file: $OPDIR/sandiego/.env

    sandiego-postgres:
        image: postgres:18.1
        shm_size: 1g # https://stackoverflow.com/questions/56751565
        container_name: sandiego-postgres
        hostname: sandiego-postgres
        restart: unless-stopped
        volumes:
            - $OPDIR/sandiego/postgres_data:/var/lib/postgresql
        environment:
            TZ: $TZ
            POSTGRES_USER: sandiego
            POSTGRES_PASSWORD: $SANDIEGO_POSTGRES_PASSWORD

    sandiego-postgrest:
        image: postgrest/postgrest:v13.0.8
        container_name: sandiego-postgrest
        hostname: sandiego-postgrest
        restart: unless-stopped
        ports:
            - 8245:3000
        depends_on:
            - sandiego-postgres
        environment:
            PGRST_DB_URI: $SANDIEGO_DATABASE_URL
            PGRST_JWT_SECRET: $SANDIEGO_JWT_SECRET

    sandiego-pgbackups:
        image: prodrigestivill/postgres-backup-local:18
        container_name: sandiego-pgbackups
        restart: always
        user: $PUID:$PGID
        volumes:
            - $OPDIR/sandiego/postgres_backups:/backups
        depends_on:
            - sandiego-postgres
        environment:
            POSTGRES_HOST: sandiego-postgres
            POSTGRES_DB: sandiego
            POSTGRES_USER: sandiego
            POSTGRES_PASSWORD: $SANDIEGO_POSTGRES_PASSWORD
            POSTGRES_EXTRA_OPTS: -Z6
            SCHEDULE: "@daily"
            BACKUP_KEEP_DAYS: 10
            BACKUP_KEEP_WEEKS: 10
            BACKUP_KEEP_MONTHS: 10
            HEALTHCHECK_PORT: 8080
#
# To-Do:
# - foundry
# - themis
