name: Docker Deploy
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:cicd,tag:privileged

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ansible/
          playbook: docker-update.yaml
          options: |
            --inventory inventory.yaml
